In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
from google.colab import drive #Connection to our student's google cloud to store the files.
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
%cd /content/drive/MyDrive/Colab Notebooks

/content/drive/MyDrive/Colab Notebooks

In [4]:
import time
start = time.time()

In [29]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split

In [7]:
df_data =    pd.read_csv('data/f1_df_final.csv')
df_data

,season,round,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,driver,grid,podium,...,constructor_minardi,constructor_prost,constructor_red_bull,constructor_renault,constructor_sauber,constructor_team_lotus,constructor_toro_rosso,constructor_toyota,constructor_tyrrell,constructor_williams
0,1983,1,False,False,True,False,False,keke_rosberg,1,15,...,0,0,0,0,0,0,0,0,0,1
1,1983,1,False,False,True,False,False,prost,2,6,...,0,0,0,1,0,0,0,0,0,0
2,1983,1,False,False,True,False,False,tambay,3,4,...,0,0,0,0,0,0,0,0,0,0
3,1983,1,False,False,True,False,False,piquet,4,1,...,0,0,0,0,0,0,0,0,0,0
4,1983,1,False,False,True,False,False,warwick,5,7,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15161,2022,22,True,False,False,False,False,kevin_magnussen,16,17,...,0,0,0,0,0,0,0,0,0,0
15162,2022,22,True,False,False,False,False,gasly,17,14,...,0,0,0,0,0,0,0,0,0,0
15163,2022,22,True,False,False,False,False,bottas,18,15,...,0,0,0,0,0,0,0,0,0,0
15164,2022,22,True,False,False,False,False,albon,19,13,...,0,0,0,0,0,0,0,0,0,1
15165,2022,22,True,False,False,False,False,latifi,20,19,...,0,0,0,0,0,0,0,0,0,1

In [23]:
df_data[(df_data['season']>2017) & (df_data['constructor_red_bull']>0)][['season','round','constructor_red_bull','driver']]

       season  round  constructor_red_bull          driver
13335    2018      1                     1  max_verstappen
13339    2018      1                     1       ricciardo
13354    2018      2                     1       ricciardo
13374    2018      3                     1  max_verstappen
13375    2018      3                     1       ricciardo
...       ...    ...                   ...             ...
15115    2022     19                     1           perez
15126    2022     20                     1  max_verstappen
15129    2022     20                     1           perez
15146    2022     22                     1  max_verstappen
15147    2022     22                     1           perez

[180 rows x 4 columns]

In [24]:
features = df_data.drop(['driver', 'podium'], axis=1)
labels = df_data['podium']
X_train, X_test, y_train, y_test = train_test_split(features,labels, test_size =0.4,random_state=42)
X_test, X_val, y_test, y_val = train_test_split(X_test,y_test, test_size =0.5,random_state=42)

In [25]:
for dataset in [y_train, y_val, y_test]:
    print(round(len(dataset)/ len(labels),2))

0.6
0.2
0.2

In [26]:
X_train

,season,round,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,grid,driver_points,driver_wins,...,constructor_minardi,constructor_prost,constructor_red_bull,constructor_renault,constructor_sauber,constructor_team_lotus,constructor_toro_rosso,constructor_toyota,constructor_tyrrell,constructor_williams
6112,1998,11,False,False,True,False,True,2,36,1,...,0,0,0,0,0,0,0,0,0,0
1765,1987,8,False,False,False,False,False,17,0,0,...,0,0,0,0,0,0,0,0,0,0
11243,2012,15,True,False,False,False,False,22,0,0,...,0,0,0,0,0,0,0,0,0,0
12824,2016,16,False,False,False,False,False,3,129,1,...,0,0,1,0,0,0,0,0,0,0
14537,2021,5,True,False,False,False,False,12,24,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5191,1995,16,False,False,False,False,False,10,11,0,...,0,0,0,0,0,0,0,0,0,0
13418,2018,5,False,False,False,False,True,10,0,0,...,0,0,0,0,0,0,0,0,0,0
5390,1996,8,True,False,False,False,False,22,0,0,...,0,0,0,0,0,0,0,0,0,0
860,1985,4,False,False,True,False,False,14,3,0,...,0,0,0,0,0,0,0,0,0,0
7270,2001,16,False,False,False,False,False,12,8,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
y_train

6112      2
1765      9
11243    17
12824     2
14537    12
         ..
5191     19
13418    18
5390     17
860      12
7270      8
Name: podium, Length: 9099, dtype: int64

In [30]:
if not os.path.exists('./data_training'):
    os.mkdir('./data_training')

In [31]:
X_train.to_csv('./data_training/train_features.csv', index=False)
X_val.to_csv('./data_training/val_features.csv', index=False)
X_test.to_csv('./data_training/test_features.csv', index=False)

y_train.to_csv('./data_training/train_labels.csv', index=False)
y_val.to_csv('./data_training/val_labels.csv', index=False)
y_test.to_csv('./data_training/test_labels.csv', index=False)